version: "3.6"
services:
  frontend:
    image: "artalexm/cloudfrontend:latest"
    ports:
      - "${FRONT_PORT}:80"

  db:
    image: 'postgres:14.2-alpine'
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      PGPASSWORD: ${DB_PASSWORD:-secret}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
    volumes:
      - "cloudstorage-db:/var/lib/postgresql/data"
    networks:
      cloudstorage:
        ipv4_address: 10.100.105.150
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}" ]
      retries: 3
      timeout: 5s

networks:
  cloudstorage:
    driver: bridge
    ipam:
      config:
        - subnet: 10.100.105.0/24
    driver_opts:
      com.docker.network.bridge.name: cloudstorage

volumes:
  cloudstorage-db:
    driver: local
